apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        # imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 5432
        env:
         - name: POSTGRES_DB
           value: "shopify"
         - name: POSTGRES_PASSWORD
           value: "090900"
         - name: POSTGRES_USER
           value: "postgres"
